name: openrgb
description: OpenRGB Dart Client to communicate with OpenRGB Server and control RGB LEDs. Protocol Version 3.
version: 0.2.5
homepage: https://github.com/Vonarian/OpenRGB

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async: ^2.9.0
  color: ^3.0.0
  quiver: ^3.1.0


dev_dependencies:
  flutter_lints: 2.0.1